spring:
  application:
    name: fashion
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/Restaurant
    username: username
    password: pass
#    driver-class-name: com.mysql.jdbc.Driver

service:
  secret-key: fashion