spring:
  application:
    name: fashion
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_schema: dbo
    database: sql_server
    show-sql: true
  datasource:
    url: ${DB_URL}
    username: ${USER}
    password: ${PASS}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

service:
  secret-key: ${SECRET_KEY}

gcp:
  credentials:
    path: ${StoreKey}
  bucket:
    name: storefile1106

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: debug